Traceback (most recent call last):
  File "/Users/caballero/anaconda3/envs/teaching/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/caballero/anaconda3/envs/teaching/lib/python3.9/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/caballero/anaconda3/envs/teaching/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/caballero/anaconda3/envs/teaching/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/caballero/anaconda3/envs/teaching/lib/python3.9/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/caballero/anaconda3/envs/teaching/lib/python3.9/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/caballero/anaconda3/envs/teaching/lib/python3.9/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from scipy.fftpack import fft, fftfreq

# Set the sample rate and time
dt = 0.0005  # Sampling frequency
T0 = 0.1 # Signal period
T = 3.0*T0  # Sample time length
t = np.arange(0, T, dt)  # Time points

fsimple = 10
Asimple = 1

simple = simple_signal(t, Asimple, fsimple)
plt.figure(figsize=(6, 4))
plt.subplot(1, 1, 1)
plt.plot(t, simple)
plt.title('Simple Signal')
plt.xlabel('Time (s)')
plt.ylabel('Amplitude')
plt.tight_layout()
plt.grid()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[11], line 12[0m
[1;32m      9[0m fsimple [38;5;241m=[39m [38;5;241m10[39m
[1;32m     10[0m Asimple [38;5;241m=[39m [38;5;241m1[39m
[0;32m---> 12[0m simple [38;5;241m=[39m [43msimple_signal[49m(t, Asimple, fsimple)
[1;32m     13[0m plt[38;5;241m.[39mfigure(figsize[38;5;241m=[39m([38;5;241m6[39m, [38;5;241m4[39m))
[1;32m     14[0m plt[38;5;241m.[39msubplot([38;5;241m1[39m, [38;5;241m1[39m, [38;5;241m1[39m)

[0;31mNameError[0m: name 'simple_signal' is not defined

